server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: root
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update           
    properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non-contextual-creation: true

ead:
  api:
    url:
      authuser: 'http://localhost:8087'
