server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LuisPaulo1/ead-config-server-repo
          default-label: master
          username: LuisPaulo1
          #password: ***

ead:
  serviceRegistry:
    username: serviceregistry
    password: '123456'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost  